"""make hashed_password nullable and add username

Revision ID: 4b8a521fda23
Revises: c5780be0a01b
Create Date: 2026-07-10 02:25:21.257758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4b8a521fda23'
down_revision: Union[str, Sequence[str], None] = 'c5780be0a01b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column('user', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # Populate existing users with username from email prefix
    op.execute("UPDATE \"user\" SET username = split_part(email, '@', 1)")
    
    # Make username non-nullable
    op.alter_column('user', 'username', nullable=False)
    
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
